language: python
python:
  - "2.7"


# command to install dependencies

install:
- pip install requests
- pip install jsonschema
- pip install simplejson
- pip install properties

# command to run tests
script:
  - sonar-scanner
  - python -m unittest discover -s test/ -p "*.py"

addons:
  sonarcloud:
    organization: "awt-01-api"
    token:
      secure: $SONAR_TOKEN



notifications:
 email: true
   - Bruno.Barrios@jalasoft.com

branches:
  only: develop