language: python
python:
  - "2.7"


# command to install dependencies
install:

# command to run tests
script:
  - sonar-scanner
  - python -m unittest test/

addons:
  sonarcloud:
    organization: "awt-01-api"
    token:
      secure: $SONAR_TOKEN



notifications:
 email: true
   - Bruno.Barrios@jalasoft.com
